apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebs-csi-controller-sa
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::492457033740:role/AmazonEBSCSIDriverRole  # replace with your IAM role ARN

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ebs-csi-controller-role
rules:
  # Allow full access to persistent volumes and claims (required for provisioning)
  - apiGroups: [""]
    resources:
      - persistentvolumes
      - persistentvolumeclaims
      - events
      - configmaps
      - pods
      - nodes
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  # Allow leader election via leases and configmaps
  - apiGroups: [""]
    resources:
       - configmaps
       - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ebs-csi-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ebs-csi-controller-role
subjects:
  - kind: ServiceAccount
    name: ebs-csi-controller-sa
    namespace: kube-system

                     